---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-deployment
  labels:
    app: spc
spec:
  minReadySeconds: 20
  replicas: 2
  selector:
    matchLabels:
      app: spc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spc
    spec:
      containers:
      - name: spc
        image: ashikrepo.jfrog.io/spc/spring_p_c:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name:  jfrogpull


---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhc2hpa3JlcG8uamZyb2cuaW8iOnsidXNlcm5hbWUiOiJhc2hpay5zaGVrMTZAZ21haWwuY29tIiwicGFzc3dvcmQiOiJBc2hpa0AxNDMxIiwiZW1haWwiOiJhc2hpay5zaGVrMTZAZ21haWwuY29tIiwiYXV0aCI6IllYTm9hV3N1YzJobGF6RTJRR2R0WVdsc0xtTnZiVHBCYzJocGEwQXhORE14In19fQ==
kind: Secret
metadata:
  name: jfrogpull
type: kubernetes.io/dockerconfigjson

---
kind: Service
apiVersion: v1
metadata:
  name: spcservice
spec:
  selector:
    app:  spc
  type:   NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  8080


