apiVersion: apps/v1
kind: Deployment
metadata:
  name: spc-deployment
  labels:
    app: spc
spec:
  minReadySeconds: 20
  replicas: 2
  selector:
    matchLabels:
      app: spc
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spc
    spec:
      containers:
      - name: spc
        image: "ashikrepo.jfrog.io/spc/spring_p_c:$BUILD_NUMBER"
        ports:
        - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: spcservice
spec:
  selector:
    app:  spc
  type:   NodePort
  ports:
  - name:  name-of-the-port
    port:  80
    targetPort:  8080


